import Footer from "@/components/general/footer";
import Navbar from "@/components/general/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="w-full">
            <Navbar />
            {children}
            <Footer />
        </div>
    );
}
